### ISSUE TITLE
Log with INFO level for client's request payload spams output

### ISSUE THREAD

**Issue by medvedNick** [near/near-jsonrpc-client-rs#105]
I believe [in here](https://github.com/near/near-jsonrpc-client-rs/blob/master/src/lib.rs#L212) using 

`log::debug!("request payload: {:#}", request_payload);`

instead of 

`log::info!("request payload: {:#}", request_payload);`

would be a better option, since the output is pretty large and rather specific. It also hides my own important logs for the info level. Another even better way is to add the ability to set log exhaustiveness from outside on client creation or by a setter

**Comment by miraclx** [comment]
Hi there, sorry for the delayed response. Yes, you're right, that was an oversight. If you can, please feel free to submit a PR. Otherwise, I should have this issue resolved in the next coming days. Thanks for reporting it!
