### ISSUE TITLE
data did not match any variant of untagged enum QueryResponseKind

### ISSUE THREAD

**Issue by mfornet** [near/near-jsonrpc-client-rs#109]
I get the following error while using workspace-rs: `Error: error while parsing method call result: [data did not match any variant of untagged enum QueryResponseKind]` After digging into this, the error seems to be produced in `near-jsonrpc-client`. 

I'm aware there is an error in the code I have that is producing this result, but it is hard to debug the error specifically, given we have no access to the actual output from the RPC. If there is an error, I suggest we attach the original response of the RPC to the error, so it is easier for developers to debug.

**Comment by miraclx** [comment]
The error should've been properly deserialized into a structured response, can you activate runtime logging and paste a copy of that?

`$ RUST_LOG=info,debug ...`

**Comment by mfornet** [comment]
You can find logs here: [Logs](https://gist.github.com/mfornet/c3c8ad69bdb745c8e04bf5f53fb6ce36).

**Comment by miraclx** [comment]
@mfornet, this error indeed came up once more in the downstream [`near-workspaces`](https://github.com/near/workspaces-rs), https://github.com/near/workspaces-rs/issues/226.

And after even further investigation, I found another reason for this. Which has been patched in #114.

[`v0.4.1`](https://github.com/near/near-jsonrpc-client-rs/releases/tag/v0.4.1) of this crate should no longer have this issue.
