### ISSUE TITLE
ApiKey::as_str() and ApiKey::to_string() are not aligned and could be misleading

### ISSUE THREAD

**Issue by frol** [near/near-jsonrpc-client-rs#115]
`ApiKey::as_str()` returns the UUID string itself while `ApiKey::to_string()` adds `x-api-key: ` prefix. This is not consistent and could mislead users.

**Comment by frol** [comment]
Yeah, I feel Display does not make a lot of sense to me

**Comment by miraclx** [comment]
What do you think about moving that behavior to the `alternate` view?

Where `{}` returns just the api key and `{:#}` prefixes it with the header key.

**Comment by miraclx** [comment]
Fair point! On that note, I'm inclined towards deprecating the `Display` impl entirely. I'll retain `.as_str()` on the other hand, and if users need a `String`, they can use `.as_str().to_owned()` as aforementioned.
