### ISSUE TITLE
ApiKey should not be limited to UUID format

### ISSUE THREAD

**Issue by frol** [near/near-jsonrpc-client-rs#116]
Why do we limit users to only UUID format of API keys? It seems we can relax this requirement and allow arbitrary String values, so I would suggest we remove UUID parsing from ApiKey construction:

https://github.com/near/near-jsonrpc-client-rs/blob/76fbf595138ed0f92d53494586f4425f536c940d/src/auth.rs#L14

**Comment by miraclx** [comment]
> Why do we limit users to only UUID format of API keys?

Pagoda Console only accepts UUIDv4 strings in that position, but yeah, this could be used outside of Pagoda Console so it makes sense to relax that requirement.
