### ISSUE TITLE
Adding send raw tx

### ISSUE THREAD

**Issue by EdsonAlcala** [near/near-jsonrpc-client-rs#156]
Hello, I'm currently working in a [chain signatures library](https://github.com/ilblackdragon/omni-transaction-rs) to create transaction payloads for multiple Blockchains (including Near itself). 

As part of the omni library, I included a way to build a signed payload for Near transactions that can be propagated.

<img width="591" alt="Screenshot 2024-09-09 at 08 29 14" src="https://github.com/user-attachments/assets/ab2da178-ff17-4630-858d-980593e9f101">

Source: https://github.com/EdsonAlcala/omni-transaction-rs/blob/master/src/near/near_transaction.rs#L37

In the image above, if you notice, the return type of `build_with_signature` is a Vec< u8 >. Then if I want to send it to a Near network using near-jsonrpc-client-rs, it won't be possible (or perhaps I'm missing something). But I saw that `send_tx` only accepts a `SignedTransaction`. However my transaction payload is already signed.

So I thought about adding a `send_raw_tx`, that only encodes to base 64 and send the payload to the network.

<img width="581" alt="Screenshot 2024-09-09 at 08 38 45" src="https://github.com/user-attachments/assets/8f6b5f65-0e73-4188-bd14-da413f51e33d">

Source: https://github.com/near/near-jsonrpc-client-rs/commit/613a0b2fcb7667da4ab8a5eceb84dd6cc2e4386a

Notice the `encode_signed_transaction` function:

<img width="652" alt="Screenshot 2024-09-09 at 08 44 02" src="https://github.com/user-attachments/assets/315f0ccd-99e1-47d1-b6fa-8b8075206e16">

You can see how I used it here https://github.com/EdsonAlcala/omni-transaction-rs/blob/master/tests/near_integration_test.rs#L91.

So my goal with this issue is:

- To check if maybe I missed something and there is a better way to do it
- If there is no way to do it right now, would my solution be appropriate and I can open a PR in this repository?

Thanks

**Comment by frol** [comment]
@EdsonAlcala I would suggest to just use `any` API in this case:

https://github.com/near/near-jsonrpc-client-rs/blob/d7ceafd0fcc36d8170ba4c730f071fb7dcbee7b5/src/methods/any/mod.rs#L39-L49

I don’t see value in adding a dedicated method for raw-transactions specifically. I believe `any` should cover it well, so I will close this issue, but if you disagree, please, reopen it
