### ISSUE TITLE
Investigate the licensing

### ISSUE THREAD

**Issue by frol** [near/near-jsonrpc-client-rs#2]
GPL is too much of an ask for just an API adapter. Let's see what brings GPL in place (nearcore project is GPL due to some heavy dependencies, which I hope we avoid in near-jsonrpc-primitives).

I hope we can arrive at MIT / Apache 2.0 license which is a good citizen in Rust ecosystem.

**Comment by miraclx** [comment]
Looking at this again, it would seem that all the direct dependencies are currently `Apache-2.0 OR MIT` although we're currently published strictly on `Apache-2.0`. I'll rectify the manifest to be more compliant.

**Comment by miraclx** [comment]
Resolved in 43aea2520270b9af6d2dbd2ca92f22a1242a3cb9, expected in the next release this weekend.

**Comment by frol** [comment]
@miraclx Great! In the future we might want to add `cargo-deny` to our CI to ensure our dependencies stay compatible with our licensing
