### ISSUE TITLE
`env::log_str` from cross contract call don't show

### ISSUE THREAD

**Issue by evergreen-trading-systems** [near/near-jsonrpc-client-rs#23]

**Comment by evergreen-trading-systems** [comment]
normal contract `env::log_str` appears in rpc response
cross-contract `env::log_str` don't show
cross-contract `panic::log_str` appears in rpc response

**Comment by frol** [comment]
@evergreen-trading-systems Where do you look for those logs? Is it rust client library bug in your opinion? Can you see the log when you do plain HTTP `tx` calls?

**Comment by evergreen-trading-systems** [comment]
i don't think this is an issue anymore. i must have resolved it. if it happens again, will reopen.
